name: Continuous Integration and Deployment
on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup DotNet 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore './secure_lib/secure_lib.csproj'

      - name: Build Application
        run: dotnet build './secure_lib/secure_lib.csproj' -c Release --no-restore
      
      - name: Unit Tests
        run: dotnet test './secure_lib.Tests/secure_lib.Tests.csproj'

      - name: Publish Application
        run: dotnet publish './secure_lib/secure_lib.csproj' -c Release -o './out'

      - name: Deploy on Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: secure-library
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET }}
          package: './out'